 host,user,remote_path,local_path
# You can comment here
192.168.1.10,your_username,/home/your_username/data,/home/perra/mnt/server1
# You can comment here
192.168.1.20,your_username,/var/www,/home/your_username/mnt/webserver

